language: python
python:
  - "2.7"
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
  - python manage.py migrate
script:
  - pep8 --exclude=migrations nagios_registration/
  - coverage run --include=nagios_registration/* manage.py test nagios_registration
after_script:
  - coveralls
