language: python
python:
  - "2.7"
install: pip install -r requirements.txt
before_script:
  - "cp travis-ci/manage.py manage.py"
  - "python manage.py syncdb –migrate –noinput"
script: python manage.py test nagios_registration
