language: python
python:
  - "2.7"
install: pip install -r requirements.txt
before_script:
  - ls -l
  - ls -l travis-ci
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
  - python manage.py migrate
script: python manage.py test nagios_registration
